### ISSUE TITLE
instana-java-opentracing will provide API to select different tracer implements?

### ISSUE THREAD

**Issue by wu-sheng** [instana/instana-java-opentracing#1]
@raphw , hello again.

Your byte-buddy is very helper for my java tracer. Also I am a contributor of OPENTRACING spec.

The Instana monitoring agent will be a javaagent? Provide a way to link to other tracer agent? I am very look forward the ability.

**Comment by CodingFabian** [comment]
Hello @wu-sheng - The Instana agent will support instrumenting calls open tracing based tracing. for that you will need to use the tracer provided in this repository, which will act as noop tracer unless you install and activate the Instana agent.
The Instana implementation of Open Tracing is compatible to and interoperable with the Instana built-in instrumentation, but not interoperable with any third party tracer, as this issue was never addressed by the open tracing spec.

**Comment by wu-sheng** [comment]
Thank you. I have known the op spec, not include this part.  But, insterested in this link. Because I will provide this ability to my tracer.

Looking forward your solution.
